# version: "3.9"

# the service that is going to run the docker file
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    # syncs code in project to code in the container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"